# Generated by Django 2.0.5 on 2018-05-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default='8dfd34df042a44a4a4d62db362015e13', primary_key=True, serialize=False),
        ),
    ]
