# Generated by Django 2.0.4 on 2018-04-10 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('89b4742b-fc1f-4b4f-8ec2-faff0e4cc7b0'), primary_key=True, serialize=False)),
                ('path', models.CharField(default='20470e02', max_length=200)),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
    ]
