# Generated by Django 2.0.4 on 2018-04-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default='2a4fbcfc', max_length=200),
        ),
    ]
