# Generated by Django 2.0.4 on 2018-04-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20180409_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default='c2dc5d2c', max_length=200),
        ),
    ]
