# Generated by Django 2.0.4 on 2018-04-10 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20180410_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb34f0db-2069-4c76-96c6-67f16f0135be'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='cbcbc5c6', max_length=200),
        ),
    ]
