# Generated by Django 2.0.4 on 2018-04-10 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20180410_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bae9a4b2-c523-48a1-b79b-72f83b263923'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='f7ec356f', max_length=200),
        ),
    ]
