# Generated by Django 2.0.4 on 2018-04-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20180410_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default='56bf37b6', max_length=200),
        ),
    ]
