# Generated by Django 2.0.4 on 2018-04-10 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20180410_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61d4a996-1e65-4ed2-904b-7492e0b50be2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='081e4516', max_length=200),
        ),
    ]
