# Generated by Django 2.0.4 on 2018-04-10 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20180410_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a3815e0-2d76-4357-8268-20abf8f5fcb7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default='8e3d6939', max_length=200),
        ),
    ]
