# Generated by Django 2.0.4 on 2018-04-10 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_auto_20180410_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='destination',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9381ceca-a7f2-4815-beb1-d91d13390f66'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='11594923', max_length=200),
        ),
    ]
