# Generated by Django 2.0.4 on 2018-04-10 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_auto_20180410_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4cd4550a-0551-41b6-8d51-cfa5c676614c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default='1ab6ed50', max_length=200),
        ),
    ]
