# Generated by Django 2.0.4 on 2018-04-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20180410_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
