# Generated by Django 2.0.4 on 2018-04-10 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20180410_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('effbf4f0-d094-4890-bb94-5c08dd3c8c06'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='24637a2f', max_length=200),
        ),
    ]
