# Generated by Django 2.0.4 on 2018-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_auto_20180410_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default='a9ec3bf813654aa78796d564afd0c1a5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='2ed92638', max_length=200),
        ),
    ]
