# Generated by Django 2.0.4 on 2018-04-10 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0010_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a58f6a3b-ffad-488a-8756-a99721c96ad9'), primary_key=True, serialize=False)),
                ('uuid', models.CharField(default='894b01ff', max_length=200)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
    ]
