# Generated by Django 2.0.4 on 2018-04-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_auto_20180410_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default='b436c319ec24412cb9cb27d06d80b9be', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='9dfd8135', max_length=200),
        ),
    ]
