# Generated by Django 2.0.4 on 2018-04-10 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='path',
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b87f95c3-3e21-4368-9955-c59e62e9f8b6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.CharField(default='77e307ca', max_length=200),
        ),
    ]
