# Generated by Django 2.0.4 on 2018-04-10 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_auto_20180410_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='uuid',
        ),
        migrations.AddField(
            model_name='link',
            name='path',
            field=models.CharField(default='30553c4f', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed5c5446-a71c-4f24-8fd7-b4b9b3c79d04'), primary_key=True, serialize=False),
        ),
    ]
