# Generated by Django 2.0.4 on 2018-04-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_auto_20180410_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default='20f45e30cd4044b1b4c1c1a657584e2c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='36e73990', max_length=200),
        ),
    ]
