# Generated by Django 2.0.4 on 2018-04-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_auto_20180410_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
