# Generated by Django 2.0.4 on 2018-04-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0014_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default='7c495260f9f741a9b8217ed062d78fb7', primary_key=True, serialize=False)),
                ('path', models.CharField(default='0f513087', max_length=200)),
                ('destination', models.URLField()),
            ],
        ),
    ]
