# Generated by Django 2.0.4 on 2018-04-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0015_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default='f0cb1eabdef84209a5d7b6fc441376c0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='9b2de552', max_length=200),
        ),
    ]
