# Generated by Django 2.0.4 on 2018-04-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0016_auto_20180410_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default='5bc6dc7e8ace47e09cd86a4cb41e90ab', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='ba5d3bda', max_length=200),
        ),
    ]
