# Generated by Django 2.0.5 on 2018-05-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0017_auto_20180410_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default='bd9d3540cc9f4277b5565d536ffa6260', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='af8e3e94', max_length=200),
        ),
    ]
