# Generated by Django 2.0.5 on 2018-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0018_auto_20180529_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.UUIDField(default='2d05c302ed8b4ed8b36ff212fc577466', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default='28410bf0', max_length=200),
        ),
    ]
