# Generated by Django 2.0.5 on 2018-05-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0019_auto_20180530_1119'),
        ('links', '0019_auto_20180530_1402'),
    ]

    operations = [
    ]
